applications:
  api:
    name: streamrecorder-api
    namespace: stream-recorder
    repoPath: streamrecorder-api
  
  network:
    name: streamrecorder-network
    namespace: stream-recorder
    repoPath: streamrecorder-network

  db:
    name: streamrecorder-db
    namespace: stream-recorder
    repoPath: streamrecorder-db

  workflow:
    name: streamrecorder-workflow
    namespace: stream-recorder
    repoPath: streamrecorder-workflow

  minio:
    name: streamrecorder-minio
    namespace: stream-recorder
    repoPath: streamrecorder-minio

  etl:
    name: streamrecorder-etl
    namespace: stream-recorder
    repoPath: streamrecorder-etl

  trino:
    name: streamrecorder-trino
    namespace: stream-recorder
    repoPath: streamrecorder-trino

  superset:
    name: streamrecorder-superset
    namespace: stream-recorder
    repoPath: streamrecorder-superset

  cluster:
    name: in-cluster